### PR TITLE
Passive count multipliers preview on nodes

### LINKED ISSUE #4850: Polymath does not affect the visual stat gain/loss on mastery nodes
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When hovering over a mastery type that is the only one I have, I expect it to show a damage loss when unallocating it due to polymath being allocated.

### What is the actual behaviour/value?

No stat changes from polymath are shown in the "(un)allocating this node will give you" section. Stats do change as expected after (un)allocating though.

### How to reproduce the issue

1. Select Polymath
2. Notice that no mastery nodes show a breakdown of stats gained from Polymath when allocating them

### Character build code

```shell
https://pobb.in/-rC1mZAakIdN
```

### Screenshots

image

### PR DESCRIPTION
**Pull request by Lilylicious**
Fixes #4850 

### Description of the problem being solved:
When building a new tree for removing/adding nodes it was not updating the values of the multipliers for notables, masteries, or mastery types.

Mastery types are reworked to count how many are allocated per type instead of simply being true, while notables and masteries are simply adjusted so they properly include a potential new/removed node in the count.

### Steps taken to verify a working solution:
- Checked elementalist Bastion of Elements (allocated notable), unclear if it works since it does not show up on tooltip regardless, but it still adds to calc tab as it should
- Attribute masteries (allocated mastery), works great
- Trickster Polymath, works great, though recover on kill does not show up on tooltip

### Before screenshot:
(With no other masteries selected)
image
(With Polymath and no other masteries)
image

### After screenshot:
(With no other masteries selected)
image
(With Polymath and no other masteries)
image

### CODE REVIEW

File: src/Modules/CalcSetup.lua [hunk 1]
```diff
@@ -484,18 +485,49 @@ function calcs.initEnv(build, mode, override, specEnv)
...
+							allocatedMasteryTypeCount = allocatedMasteryTypeCount + 1
+						else
+							local prevCount = allocatedMasteryTypes[node.name]
+							allocatedMasteryTypes[node.name] = prevCount + 1
+							if prevCount == 0 then
+								allocatedMasteryTypeCount = allocatedMasteryTypeCount + 1
+							end
+						end
+					elseif node.type == "Notable" then
+						allocatedNotableCount = allocatedNotableCount - 1
```
Comment (Nostrademous) [inline src/Modules/CalcSetup.lua:502]: this should be ` + 1`

**Review by Nostrademous — CHANGES_REQUESTED** [review]

**Review by Nostrademous — APPROVED** [review]

**Comment by Nostrademous** [comment]
LGTM

**Review by LocalIdentity — APPROVED** [review]
