### PR TITLE
fix totems not being affected by auras

### LINKED ISSUE #4550: Totems aren't affected by defensive auras in PoB
"Tested and works as expected. It's worth noting though that resistances from auras (Purity of Elements, etc) should probably affect totems the same way they currently affect minions."

_Originally posted by @Lothrik in https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/4523#issuecomment-1179731205_

### PR DESCRIPTION
**Pull request by Paliak**
Fixes #4550 .

### Description of the problem being solved:

Handle totems being affected by player auras and correct calculations for Forbidden right and Righteous Fire.

### Link to a build that showcases this PR:
`https://pobb.in/s9LAfsKONJuO`

### Before screenshot:
before

### After screenshot:
after

### CODE REVIEW

File: src/Modules/CalcOffence.lua [hunk 1]
```diff
@@ -1599,6 +1601,13 @@ function calcs.offence(env, actor, activeSkill)
 				output.Speed = output.Speed * globalOutput.ActionSpeedMod
 				output.CastRate = output.Speed
 			end
+			if skillFlags.totem then
+				-- Totem skill. Apply action speed
```
Comment (deathbeam) [inline src/Modules/CalcOffence.lua:1605]: there is no source of action speed for totems afaik and tailwind do not works on them.

Comment (Paliak) [reply src/Modules/CalcOffence.lua:1605]: > Totems still use their summoner's skills. For an offensive aura to have an effect, it must affect the summoner, not the totem. Action Speed benefits like [Tailwind](https://www.poewiki.net/wiki/Tailwind) are the one main exception and affect the totem directly.

From https://www.poewiki.net/wiki/Totem

Also @Lothrik said the same on discord.

Comment (Lothrik) [reply src/Modules/CalcOffence.lua:1605]: To be slightly more specific: the Tailwind effect from Deadeye's ascendancy node affects both the player *and nearby allies*. This means it will grant things like minions and totems action speed. Tailwind from other sources only ever affects the player. The Flow Untethered and Slipstream are two other examples of action speed sources that affect units beyond the player.

**Comment by Lothrik** [comment]
I came across this (while looking for something else) in the 3.13.0 patch notes and it definitively proves action speed is supposed to affect totems:
``Fixed a bug where the action speed buff granted by the Greater Harbinger of Time from The Flow Untethered and The Torrent's Reclamation unique items did not affect your totems.``

**Review by Nostrademous — APPROVED** [review]

**Comment by Nostrademous** [comment]
LGTM

**Review by LocalIdentity — APPROVED** [review]
