### PR TITLE
Fix Bleed/Ignite Stack potential issues

### LINKED ISSUE #6366: Ignite acting incorrectly with less 1 stack potential
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### How is Path of Building expected to behave?

Ignite dps should be found using (base dps*burn rate*effective dps mod).  Note that in my case, ignites are being refreshed through the "defiled forces" node, so ignite duration is irrelevant.

### How does Path of Building behave?

Ignite dps is lower than expected, based on the detailed calculation numbers.  For me it says 444k*1.46*1.77=682k

### How to reproduce the issue

Choose vortex with shaper of flames.
Lower ignite duration to under 1 stack potential (I used replica emberwake).
Look at "Ignite DPS".
Note, Manually overriding "stack potential" does not fix the issue.

### Character build code

```shell
https://pobb.in/aj9ZwSQLXh_0
```

### Screenshots

3e9ef5740631a16f69c98b30a7b40f7d

### PR DESCRIPTION
**Pull request by LocalIdentity**
The config was not affecting the number of bleeds/ignites affecting the enemy and was instead only affecting the average roll %
Ignite and Bleed roll % was not calculated to be at least 50% roll as a minimum
Ignite was also not taking into account Hit Chance when calculating the average roll
Breakdowns were improved to show the potential when max stacks is more than 1
Fixes #6366

### CODE REVIEW

File: src/Modules/CalcOffence.lua [hunk 1]
```diff
@@ -4125,20 +4136,26 @@ function calcs.offence(env, actor, activeSkill)
 			local igniteStacks = 1
 			if not skillData.triggeredOnDeath then
 				if output.Cooldown then
-					igniteStacks = (globalOutput.IgniteDuration / m_max(output.Cooldown, (output.HitTime or output.Time)) * skillData.dpsMultiplier) / maxStacks
+					igniteStacks = ((output.HitChance / 100) * globalOutput.IgniteDuration / m_max(output.Cooldown, (output.HitTime or output.Time)) * skillData.dpsMultiplier) / maxStacks
```
Comment (Aryk-st) [inline src/Modules/CalcOffence.lua:4139]: I'm pretty sure dividing by maxStacks here and than calculating 

`local igniteRollAverage = igniteStacks / (igniteStacks + 1) * 100`

is not correct.

If we apply 10 stacks per duration and have maximum stacks of 2, current calculations give 
`stack potential = 10 / 2 == 5`
`igniteRollAverage =  5/6 * 100 == 83.3%`

while the correct value is the average of 10/11 and 9/10 == 90.45% -- two most powerful ignites currently.

It also undervalues ignites with low uptime. If your ignite duration is 0.1s and you can apply 1 stack per second igniteStacks will be 0.1 resulting in average roll of 9% which is not true, average roll will be 50%

Comment (Aryk-st) [reply src/Modules/CalcOffence.lua:4139]: Also was looking at https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues/6272 and realized that igniteStacks here should also address ignite chance. Otherwise reducing ignite chance increases damage as potential stays unchanged and calcs think that more of ignites are from crits now

Comment (LocalIdentity) [reply src/Modules/CalcOffence.lua:4139]: I agree with your comments and will fix them for a future PR but I need to merge this now for the next update
