### PR TITLE
Use Default value for loadout with no set name match

### LINKED ISSUE #7790: Adding {1} to a list item in every tab results in an error and no linked loadout
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

By appending {1} to the end of list item names in all 4 tabs a loadout should be created

### How does Path of Building behave?

изображение
I added {1} to a tree, skill setup, gear setup and config setup, on saving the last one it shows an error and does not link the loadout

### How to reproduce the issue

Take a pob with multiple saved trees, skill setups, etc
Try to link a loadout by appending {1} to the end of names

### Character build code

```shell
https://pobb.in/_uzI5QJEoaKh
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by deathbeam**
Closes #7790

### Link to a build that showcases this PR:

https://pobb.in/tzW3NSwDzqo8

### CODE REVIEW

File: src/Modules/Build.lua [hunk 1]
```diff
@@ -937,7 +937,7 @@ function buildMode:SyncLoadouts(reset)
 				if linkIdentifier then
 					for linkId in string.gmatch(linkIdentifier, "[^%,]+") do
 						transferTable["setId"] = set
-						transferTable["setName"] = string.match(setTitle, "(.+)% {")
+						transferTable["setName"] = string.match(setTitle, "(.+)% {") or "Default"
```
Comment (Wires77) [inline src/Modules/Build.lua:940]:
```suggestion
						transferTable["setName"] = string.match(setTitle, "(.+)% *{")
```

This was going to be my fix, but yours works too.

**Review by Wires77 — APPROVED** [review]

File: src/Modules/Build.lua (hunk 1 above)
Comment (deathbeam) [reply src/Modules/Build.lua:940]: I actually did that at first but it doesnt work because string.match still returns nil if the string is just empty
