### PR TITLE
Fix issue importing Fobidden Flame/Flesh

### LINKED ISSUE #4117: Forbidden Flame/Flesh are working in game, not in PoB Fork in my case.
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I should see DPS increase from Mastermind of Discord node allocation.

### What is the actual behaviour/value?

I can't see DPS increase.

When I move cursor on 'actual' Elementalist's Mastermind of Discord gives me extra dps increase in green numbers, but Mastermind of Discord from [Forbidden Flame + Flesh] is not reflected in the results.

### How to reproduce the issue

You can easily check that from link below

### Build code

```shell
https://pastebin.com/DKbxYe2K

This is my actual character and it works in game, only not on PoB
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Nostrademous**
Fixes #4117:

Provides Support for:
- Copy/Paste of Forbidden Flame/Flesh from PoE Trade `https://www.pathofexile.com/trade/search/Archnemesis/rjD3VPESQ`
- Parsing of Character Import with from PoE with Forbidden Flame/Flesh item requirements block
- Updated PoE changes to the item (they changed from it being a `Prismatic Jewel` to `Cobalt` for Flesh and `Crimson` for Flame, they changed the modifier string very very slightly

To Test:
Use PoE.Ninja to find a character that has Forbidden Flame or Flesh and import.

### CODE REVIEW

File: src/Classes/Item.lua [hunk 1]
```diff
@@ -184,6 +184,10 @@ function ItemClass:ParseRaw(raw)
 			if not specName then
 				specName, specVal = line:match("^(Requires Class) (.+)$")
 			end
+			if not specName then
+				specVal = line:match("^Class:: (.+)$")
```
Comment (Wires77) [inline src/Classes/Item.lua:188]: GGG, please....

**Review by Wires77 — APPROVED** [review]
