### PR TITLE
Fix Explosive Arrow Full DPS

### LINKED ISSUE #2486: Full DPS for explosive arrow might be incorrect
Currently running version 2.0.3
PoB link for reference: https://pastebin.com/E23vv6xZ

When I tick "Include in Full DPS" for my explosive arrow, the DPS shown seems way too high. My average hit at 20 fuses is ~281k, but the full DPS shows it at ~7.1mil. I have nothing else ticked to include in full DPS.

The 7.1mil shown under full DPS seems to be assuming the average hit is per fuse. 
Given that I can reach the 20 fuse cap 1.27 times per second: `281,796.3 * 20 = 5,635,926 × 1.27 = 7,157,626.02` 
This math seems to line up with what I'm given for full DPS. If I go to any of the other fuse options, I can get the given full DPS number exactly the same way. It multiplies the average hit by 20, and then by 1.27.

My assumption was that that the average hit is already counting the given amount fuses together. This would mean I should have a full DPS of about 357k.

Because I don't know for sure if the average hit is counting all the fuses together or not, I can't really tell if this is bugged or not. But with how easily I can scale the full DPS into the tens of millions, I'm assuming it's bugged.

### PR DESCRIPTION
**Pull request by AnSq**
Fixes #2486

### Description of the problem being solved:

When "Include in Full DPS" is checked for Explosive Arrow, currently PoB doesn't give it any special treatment and simply takes the "Average Damage" (of an explosion) times Attack Rate (the rate that you apply *fuses*) to get DPS. The correct calculation is Average Damage times Explosion Rate. This change implements a calculation for Explosion Rate, shown as "Hit Rate" in PoB.

The time between explosions (HitTime) is either the skill duration, or the time it take to reach the fuse limit, whichever is lower. The time to max fuses is:

    timeToMaxFuses = fuseLimit / (hitChance * attackSpeed * totemLimit * barrageProjectiles)

The calculation is done in `explosiveArrowFunc()`, which lives on the skill itself and kinda looks like a preFunc, but it needs access to information that's not available to the preFuncs. I also pulled the Maximum Sustainable Fuses calculation into this new function.

### Screenshots

dps

### Link to a build that showcases this PR:

This is the build used in the above screenshots: https://pobb.in/m4qGXNAjPT89

### CODE REVIEW

**Comment by AnSq** [comment]
This relates to #2486 (though I'm still unclear exactly how).

**Comment by QuickStick123** [comment]
I think explosiveArrowFunc() would be a more reasonable name no need to weirdness

**Comment by AnSq** [comment]
> I think explosiveArrowFunc() would be a more reasonable name no need for weirdness

Good call.

This should also work for Barrage Support now, which fixes #2486.

**Comment by QuickStick123** [comment]
You have some conflict you need to fix @AnSq.

File: src/Data/Skills/act_dex.lua [hunk 1]
```diff
@@ -3744,6 +3744,55 @@ skills["ExplosiveArrow"] = {
...
+		local duration = calcSkillDuration(skillModList, activeSkill.skillCfg, activeSkill.skillData, env, enemyDB)
+		local fuseLimit = skillModList:Sum("BASE", activeSkill.skillCfg, "ExplosiveArrowMaxFuseCount")
+		local activeTotems
+		if activeSkill.skillFlags.totem then
+			activeTotems = modDB:Override(nil, "TotemsSummoned") or skillModList:Sum("BASE", activeSkill.skillCfg, "ActiveTotemLimit", "ActiveBallistaLimit")
+		end
+
+		local barrageProjectiles = nil
+		if skillModList:Flag(nil, "SequentialProjectiles") and not skillModList:Flag(nil, "OneShotProj") and not skillModList:Flag(nil,"NoAdditionalProjectiles") and not skillModList:Flag(nil, "TriggeredBySnipe") then
+			barrageProjectiles = skillModList:Sum("BASE", skillCfg, "ProjectileCount")
```
Comment (Lilylicious) [inline src/Data/Skills/act_dex.lua:3765]:
```suggestion
			barrageProjectiles = skillModList:Sum("BASE", activeSkill.skillCfg, "ProjectileCount")
```
Without specifying the config properly, you're missing 4 projectiles.
