### PR TITLE
fix(7622): store widowhail multiplier & apply to clones

### LINKED ISSUE #7622: Widowhail does not work with BAMA Clones
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### How is Path of Building expected to behave?

When using widowhail the clones should get mulitplied stats from the quiver as well as the player.

### How does Path of Building behave?

When equipping wiowhail only the player gets multiplied stats form the quiver, the clones do not get anything from it.

### How to reproduce the issue

1. equip any bama gem
2. equip widowhail
3. equip any quiver with flat damage
image
4. make a white crude bow, swap it with widowhail
image
=> Only player stats change

### Character build code

```shell
https://pobb.in/Q1bvbkFDWk4J
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by FWidm**
Fixes #7622  .

### Description of the problem being solved:
widowhail multiplier only applied to the player not the minions as well

### Steps taken to verify a working solution:
- checked widowhail minion pob
image
- checked widowhail non minion pob (values stay the same)
image

### Link to a build that showcases this PR:
- minion: https://pobb.in/Q1bvbkFDWk4J
- non minion: https://poe.ninja/builds/necropolis/character/Spirituus/Spirituus_Bait_Again?i=6&search=items%3DWidowhail

### CODE REVIEW

**Comment by FWidm** [comment]
tests seem to fail but i cant really decipher what the issue is, doesnt seem related to my small change, feel free to adapt anything.

File: src/Modules/CalcPerform.lua [hunk 1]
```diff
@@ -1005,7 +1005,7 @@ function calcs.perform(env, skipEHP)
 				env.minion.modDB:AddList(env.player.itemList["Weapon 1"].slotModList[1])
 			end
 			if env.player.itemList["Weapon 2"] and env.player.itemList["Weapon 2"].type == "Quiver" then
-				env.minion.modDB:AddList(env.player.itemList["Weapon 2"].modList)
+				 env.minion.modDB:ScaleAddList(env.player.itemList["Weapon 2"].modList, env.widowHailModifier or 1)
```
Comment (Nightblade) [inline src/Modules/CalcPerform.lua:1008]: There appears to be an extra space after the indentation tabs?

Comment (FWidm) [reply src/Modules/CalcPerform.lua]: ty, fixed

File: src/Modules/CalcSetup.lua [hunk 2]
```diff
@@ -991,7 +991,9 @@ function calcs.initEnv(build, mode, override, specEnv)
 					end
 					env.itemModDB:ScaleAddList(srcList, scale)
 				elseif item.type == "Quiver" and items["Weapon 1"] and items["Weapon 1"].name:match("Widowhail") then
-					scale = scale * (1 + (items["Weapon 1"].baseModList:Sum("INC", nil, "EffectOfBonusesFromQuiver") or 100) / 100)
+					local widowHailMod=(1 + (items["Weapon 1"].baseModList:Sum("INC", nil, "EffectOfBonusesFromQuiver") or 100) / 100)
+					scale = scale * widowHailMod
+					env.widowHailModifier = widowHailMod
```
Comment (Paliak) [inline src/Modules/CalcSetup.lua:996]: Nitpicking but not sure how i feel about adding modifiers directly to the env table. Something like this would be a bit cleaner imo:

```diff
diff --git a/src/Modules/CalcPerform.lua b/src/Modules/CalcPerform.lua
index 1bc2ad95c..9a591e90c 100644
--- a/src/Modules/CalcPerform.lua
+++ b/src/Modules/CalcPerform.lua
@@ -1005,7 +1005,7 @@ function calcs.perform(env, skipEHP)
                                env.minion.modDB:AddList(env.player.itemList["Weapon 1"].slotModList[1])
                        end
                        if env.player.itemList["Weapon 2"] and env.player.itemList["Weapon 2"].type == "Quiver" then
-                               env.minion.modDB:AddList(env.player.itemList["Weapon 2"].modList)
+                               env.minion.modDB:ScaleAddList(env.player.itemList["Weapon 2"].modList, m_max(modDB:Sum("BASE", nil, "WidowHailMultiplier"), 1))
                        end
                end
                if env.minion.itemSet or env.minion.uses then
diff --git a/src/Modules/CalcSetup.lua b/src/Modules/CalcSetup.lua
index 560b8c9d6..602475497 100644
--- a/src/Modules/CalcSetup.lua
+++ b/src/Modules/CalcSetup.lua
@@ -991,7 +991,9 @@ function calcs.initEnv(build, mode, override, specEnv)
                                        end
                                        env.itemModDB:ScaleAddList(srcList, scale)
                                elseif item.type == "Quiver" and items["Weapon 1"] and items["Weapon 1"].name:match("Widowhail") then
-                                       scale = scale * (1 + (items["Weapon 1"].baseModList:Sum("INC", nil, "EffectOfBonusesFromQuiver") or 100) / 100)
+                                       local widowHailMod=(1 + (items["Weapon 1"].baseModList:Sum("INC", nil, "EffectOfBonusesFromQuiver") or 100) / 100)
+                                       scale = scale * widowHailMod
+                                       env.modDB:NewMod("WidowHailMultiplier", "BASE", widowHailMod, "Widowhail")
                                        local combinedList = new("ModList")
                                        for _, mod in ipairs(srcList) do
                                                combinedList:MergeMod(mod)

```

Comment (FWidm) [reply src/Modules/CalcSetup.lua:996]: I'm fine with either, maintainers can decide. I am not deep enough into POB dev to know which one is more clean :)

**Review by LocalIdentity — APPROVED** [review]
