### PR TITLE
PoB Trader: Fix issues caused by sorting mode change

### LINKED ISSUE #5542: Crash upon changing search method after searching for best jewel
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

image

### What are your system specifications and configuration?

Lua Crash

### How to reproduce the issue

1. Search for best jewel
2. Change sort method

Reported on discord by nostrademous
### Character build code

```shell
https://pobb.in/v4-YpzMtsz8J
```

### PR DESCRIPTION
**Pull request by Dullson**
Fixes #5542, #5544

### Description of the problems being solved:
- Fixed a crash caused by sort mode change when jewels are present
- Fixed error message not clearing after successful sort
- Fixed `Import Item` button tooltip not displaying selected dropdown item after sorting

### CODE REVIEW

**Comment by QuickStick123** [comment]
I also included a fix fir the import button in #5375 but this seems to fix it differently.

File: src/Classes/TradeQuery.lua [hunk 1]
```diff
@@ -464,13 +464,15 @@ function TradeQueryClass:UpdateControlsWithItems(slotTbl, index)
...
-	if errMsg then
+	elseif errMsg then
 		self:SetNotice(self.controls.pbNotice, "Error: " .. errMsg)
 		return
+	else
+		self:SetNotice(self.controls.pbNotice, "")
 	end
+
 	self.sortedResultTbl[index] = sortedItems
-	self.itemIndexTbl[index] = 1
```
Comment (Dullson) [inline src/Classes/TradeQuery.lua:473]: > I also included a fix fir the import button in #5375 but this seems to fix it differently.

Didn't check that PR yet but this line was wrong and had to be fixed. Looks like the intention was to reset the item index to 1 after sorting because dropdowns reset but the sorted item indexes are a little more convoluted than that. This is the correct way to reference the item on the first slot of dropdown containing sorted items.

**Comment by QuickStick123** [comment]
Doesn't fix #5544 afaik as it seems to be caused by using certain trade urls in the price item thing. Such as 
https://www.pathofexile.com/trade/search/Sanctum/3vWZdmJh5

**Comment by Dullson** [comment]
Now it should fix #5544

**Review by LocalIdentity — APPROVED** [review]
