### PR TITLE
PressurePoints fix

### LINKED ISSUE #367: Implement Pressure Points Notable
First mod is not parsed

```
Your Critical Strikes have a 5% chance to deal Double Damage
40% increased Critical Strike Chance
```

### PR DESCRIPTION
**Pull request by Nostrademous**
Fixes #367 

Removes need for old PR #488

### CODE REVIEW

File: Modules/CalcOffence-3_0.lua [hunk 1]
```diff
@@ -1049,20 +1055,20 @@ function calcs.offence(env, actor, activeSkill)
...
+			local critChancePercentage = output.CritChance / 100
+			output.CritEffect = 1 - critChancePercentage + (critChancePercentage * output.CritMultiplier * output.CritDoubleDamageEffect)
 			output.BonusCritDotMultiplier = (skillModList:Sum("BASE", cfg, "CritMultiplier") - 50) * skillModList:Sum("BASE", cfg, "CritMultiplierAppliesToDegen") / 10000
 			if breakdown and output.CritEffect ~= 1 then
 				breakdown.CritEffect = {
-					s_format("(1 - %.4f) ^8(portion of damage from non-crits)", output.CritChance/100),
-					s_format("+ (%.4f x %g) ^8(portion of damage from crits)", output.CritChance/100, output.CritMultiplier),
+					s_format("(1 - %.4f) ^8(portion of damage from non-crits)", critChancePercentage),
+					s_format("+ [ (%.4f x %g) ^8(portion of damage from crits)", critChancePercentage, output.CritMultiplier),
+					s_format("  x (%.4f) ] ^8(double damage inc on crit)", 1+(output.CritDoubleDamageChance/100)),
```
Comment (ppoelzl) [inline Modules/CalcOffence-3_0.lua:1065]: There are still formatting issues on this line.
