### PR TITLE
fix: allow account names with dashed in them to be imported correctly

### LINKED ISSUE #8369: Dashes in account names are wrongly replaced with discriminator hashes
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### What platform are you running Path of Building on?

Windows

### How is Path of Building expected to behave?

The following (not mine) profile should be importable:

https://www.pathofexile.com/account/view-profile/Dj-Reck1-9507

`Dj-Reck1#9507` is not importable currently.

I think I have identified the issue, and it seems to me this change does not work in all cases, and a more sophisticated approach should be used.

https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/8361/files#diff-9c92f7ea8e0528b99067d974565d47e61b86fb3c1eb98961299b511f9be7fe5bR458

Since I am not a lua dev I'd like to just place this here, and maybe take a shot at it later or tomorrow, else this is up for grabs

### How does Path of Building behave?

Fetch failed, account is private is shown.

image

### How to reproduce the issue

Import Dj-Reck1#9507

### Character build code

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by tarekis**
Fixes #8369.

### Description of the problem being solved:
Accounts with dashes in them (e.g. `Dj-Reck1#9507`) could not be imported.
Those accounts are possible because dashes are allowed in account names for consoles.

### Steps taken to verify a working solution:
- Import `Dj-Reck1#9507`
- Import `Dj-Reck1-9507`
- Import `Tarekis#5639`
- Import `Tarekis-5639`

Hope code looks good to yall. Not a lua dev lol

### CODE REVIEW

File: src/Classes/ImportTab.lua [hunk 1]
```diff
@@ -1138,6 +1139,24 @@ function HexToChar(x)
 	return string.char(tonumber(x, 16))
 end
 
+function ReplaceCharAtIndex(str, pos, r)
+    return ("%s%s%s"):format(str:sub(1,pos-1), r, str:sub(pos+1))
```
Comment (Nightblade) [inline src/Classes/ImportTab.lua:1143]: This line is space-indented; should be tab.

**Comment by Regisle** [comment]
This looks like it works from the few tests I did, but is a little overkill, as the `-` will always be the 5th character from the end if its used for the discriminator. (discriminator is always the last 5-7 characters)

Also a helper function like `ReplaceCharAtIndex` should probably go in common.lua incase its actually something we will use in other places.

**Comment by clemenshimmer** [comment]
I totally agree with moving `ReplaceCharAtIndex`. I overlooked `common.lua`.

I did the discriminator char index search this over-engineered because it would be forward-compatible to GGG having to adapt to thing like long character names and discriminators being anything other than 4 characters.  Since it's not run very often I figured the overkill would be okay for the benefit of also addressing those potential discriminators.

Fixing indent and `ReplaceCharAtIndex` into common as soon as I'm on a machine I can work with

**Comment by tarekis** [comment]
Moved `ReplaceCharAtIndex `and fixed indent.

File: src/Classes/ImportTab.lua [hunk 2]
```diff
@@ -1138,6 +1139,20 @@ function HexToChar(x)
...
+	reversedAccountName = string.reverse(accountName)
+	discriminatorIndex = 0
+	for i = 1, #reversedAccountName do
+		local c = reversedAccountName:sub(i,i)
+			if c == "#" or c == "-" then
+			discriminatorIndex = i
+			break
+			end
+	end
+	discriminatorIndex = discriminatorIndex * -1
```
Comment (Wires77) [inline src/Classes/ImportTab.lua:1152]: FYI, you don't have to reverse the string and the index here, just put your for loop in reverse instead
```suggestion
	discriminatorIndex = 0
	for i = #accountName, 1  do
		local c = accountName:sub(i,i)
			if c == "#" or c == "-" then
			discriminatorIndex = i
			break
			end
	end
```

File: src/Classes/ImportTab.lua [hunk 3]
```diff
@@ -424,7 +424,8 @@ function ImportTabClass:DownloadCharacterList()
 		accountName = self.controls.accountName.buf:gsub("^[%s?]+", ""):gsub("[%s?]+$", ""):gsub("%s", "+")
 	end
 	local sessionID = #self.controls.sessionInput.buf == 32 and self.controls.sessionInput.buf or (main.gameAccounts[accountName] and main.gameAccounts[accountName].sessionID)
-	launch:DownloadPage(realm.hostName.."character-window/get-characters?accountName="..accountName:gsub("-", "%%23"):gsub("#", "%%23").."&realm="..realm.realmCode, function(response, errMsg)
+	accountName = ReplaceDiscrimintorSafely(accountName)
```
Comment (Wires77) [inline src/Classes/ImportTab.lua:427]: Does this behave fine when saving previously imported accounts in settings?

**Review by Wires77 — COMMENTED** [review]
Not at a computer I can test this at until later, but looks good to me in general.

File: src/Classes/ImportTab.lua (hunk 2 above)
Comment (tarekis) [reply src/Classes/ImportTab.lua]: Didn't know that was possible in lua, cool stuff, but I see you removed it anyways.

`gsub` not working with regex totally did not click in my brain, props for finding a better shorthand.
