### PR TITLE
Fix ignite with cast on death

### LINKED ISSUE #4391: Cast On Death Ignite Damage Broken
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

Ignite damage calculation is wrong by a factor of ~15000 when linked with cast on death.
The example displays ignite dps 2.5.

### What is the actual behaviour/value?

Should be ~30000 instead.

### How to reproduce the issue

Just link cast on death and check ignite dps.

### Character build code

```shell
eNqtWm1z2rgW_lx-hYaZe6edKeB3SDbZHULIy0xIWUjavZ86ii1AjWxRWyalO_3v90g2YBIMwrvdma6xn_P26JyjI7tnf_wIGVqQOKE8Oq-bTaOOSOTzgEbT8_rjw1WjU__j99rZEIvZp8lFSpl88nvt3Zm6RowsCAO5OhI4nhLxeaXJ_gqa5jgSM8KjAf7G42senNfveUTq6AlHARWrXz7DSXKPQ3Je_0KFP6sjnPgkCnqb-31GQhIJzGgi6ijENBpz_5mI65inc2V-QcnLgAeAvR0MP40eCsZpVDQOvr87GzK8JPFYYIES-Ou83gUK8JTcUFC_wCwFPbbluk6zbbn11m6Z8ZyQYA03m17hT5s0jFLBYUz6kwnxBV2QXkxFb4Yjn2w0GU2rTLQCfJAyQeeMkrjga6lvDxxYvhyO11ij6TqW2-60D4jwDXNGGfJ2GlFBitqtpms7ru05tmU5nfYBQRzCGhUDN-2O6bhtq3NyctC9CmZ7KWOQ7lt0lGJ5-EQjEnQX02IKeU6z49nKyZMy0W5M8KdJlhIjHNA0WWsolRngCPd4okH6HZ0QPWR_rIcbwSroIaWXQxJDNQt9Z48SyC2Mic-hYxxj4xiRQhzVjFWQ7I-rCFQwNBaFzuCULjr5vgU07TLkJfmhp68IbJc3jajYk_eoKwJN1y13b8EF7FGHiVGdo38zXCO9dhN6xsmJd2IaxolXSqgiH_YdGmI2wD9omIawszzgZ7KxartNr3xvkWmzhrrtPVuQfyqxt5Gvl4uPUUwSEi8KO1e5-m2BPLsK_XevpRGZkkjPqTtC_Nk17OpgorgFu832vorc4Ly9BEmsFkESuIsgT0_gCIKk4DZB5j5oGUGl-r_gONDoGBGJp8vxjBKmgVZcFkW0OC0KaKZEUeToyPsLnBSr23T3x5PB9dKDMEJAICCvRjCjfNLj3-Scx44T68YhT2PNFcnAWgEMZ8uE-jANqUFqRILU1-uE63F1wBdqElezL8zbh9P3gsGk_npk3bcmjO0SKedKCOw_X_Jgqk2vMnK8xDidz6HUZbroyl3RGGhOaGEbbnga6E9wHOnhuc7UKatK18AGrW3gjk5nIoIhWN_KKxH9WGaYJ0cEs4Frm7iCgV5rmh_yF1A5k2fa5Dg07PebPb7Uj5hEP5fa-rfgWgb6UZDGMke1bbyWeGvmrKXO_PLqNpzzWKibPcz8RKm8jeapQJE6sIc08b8-pZOJPJPXwUSsXij0r676vYfbz_3ci6JI8kwZ-xql4ZM8qWb_3_SVMVGtCvmcMTxPCBznI8rqiMLFWEqOoTn7QgMNu0h-kDyMhW3UjynQdxgqD8Aarqp3Bodx8uCuAYN1wIzoUvSwnBO54okeS3mTO4y9YHpBDTlNYLfRCEsd93VIJz5eauDWU4QGts9IlzK5yenwNIBEz3ZHHTRsVjF9SoVWRqkzgIYHchLWCKs462llvg4sn1Q0zOdj2WFkvgPopB2MCZpLdEkmBJJZq5BVc8gOa1nbW7W4M1VFCUqg912TMLlYwl5yJQndvP5Ru0uIBaQbCe_k29EHLjsq9gWJ77K3pRPMEtkUi2rO6yJO4WZAJjhl8v6fKWZULGXLLtzNVShvkxl_kUNJpkdWdwIrcneXPekykauQRlZWs_BlHOo1aldNdeq3ilK9S6WRz9IAzpT5dpmbY_hJmq6jqXzr2uNpJPInJMJPTJKYxfBKsdQpzb47A0dy7DXjT5hZK81ZUJZR33psrhSqreE2yCYkeMDyW_KIDbO7IOGYCOX69yziW9UbFGc5dIjjDDEloXw6IAIHWOCWlE5akqKW8hauNla-F9bgVZBrrRve_IwSuJI7mhzOSzyGfpyGIYd0GRE8J3n9_Av85NnQwzATRZcEi9luSvaRsE6oXVp2MbErbCmLoMAy6azoMn5VRWWFJC8fYkIQzpJFSZp5isKP4ncA6a4lUyuBOlrmHVcmYwQDhqTfatudj6ZnWPZH13Gc9kfXNi27jgQYKHyVMDv5Bwep0M7zsh_AdhPcS035SjyO7tTFu5kQ8-S01Xp5eWnOIRY-IT_gONf0ediagxrwu6Hob0hDrS78uZgOet1vN72fzgB-nZ8rha2VxrPsy0Wy4gTiVJRIIuTFPYfdQT6TN1c_FE2fKXlBCYGRZDYWsYz9J-fh_87rTsdsnnQ8q9NxbcuzsvK_AeYHeJ5nkETmrcPOGwcMApcUeIxVY1wtpgT-BXO3azWtE7ftWKZhmV4-AKo0yVerWHVpQrJ3Xl8gnXmkbkuz2YwHQBgkY4plllhZk807wghui-Upery__fOxX7vk8RJH9L-gJPktQT1ITbZMRO0zxgyNfTIHjuGHUnWKhjFBVtNuGptbvTSGcEQtGwZJgNZPrG0leWeE-0YtX5BTdNGA_2qKphH5forabg0GLEZ9Kp9atb_zKE7NX6bxH9kmY4Jh80Drz1Mo2zw2SOuXbe1FZsbhybWiFkLKCxBuPS2zygcnC4LDmDOYDGIsd7Da3zCzT8mp0XR_dYMgQe89t9FxPyDB0XvTMBpQER_Q6ty_dm8j9N40G6b7oehjdqJGalTdgnoN09hCqip_i7ONhrMNzPoVklOt8gPylz4TlE2YNaMJHPHJG3KQGttAHCdIDkMrI-av9x2IzNi28YZaWWxw_BhJGaQk1desLAGdVc8tRbgHEd5BRLsMYWbPV593VAPO-h7jqwNRVkxIQkXWr9eHoTcg6y0oL9DS4izW4S6z4xc8R92nZZLIBVNpityNGWMV2g7R12KWntibGLZQF5yLpKJDu2I54NQFYeJIkSvYV56RreWStcsluxq9eiRY_5KYU81Jr5o1rzqb5oEF3pVPB1bghsDBUBxraEcmeVXsHEg_aLIL-abneMV29Soyq9hzquWCWS3znMPLo0PssWp3pVfFwLX6jlvBnwo90D5kJlii7K3Akcu3m-VK-eVWEdIqSZ2FqBSnW5lWq8K6e9Uqya6WvvbxWeZUb_sVctqsTL6tkxCODqiC2_9g-NFcyf0T2b5V8CpkZfVl-AfpotuSpaxm1ehDKzA3otFUbxI4ulGU0luxXeivZ5VwbA2ezOrL4FRmy60SjU69VE_yAy51w5Tt2NuyYykcGNULKvXyR33x49GETgFx1nr9z4L_D1sp2Ck=
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by QuickStick123**
Fixes #4391.

### Description of the problem being solved:
Due to the weighted average formula and cast on death trigger time being 60 seconds this results in an extremely low stack potential when we should just get one ignite stack.

### Steps taken to verify a working solution:
- See ignite dps in appropriate range ~30k

### Link to a build that showcases this PR:
https://poe.ninja/pob/AnD

### Before screenshot:
image

### After screenshot:
image

### CODE REVIEW

File: src/Modules/CalcOffence.lua [hunk 1]
```diff
@@ -3210,7 +3210,11 @@ function calcs.offence(env, actor, activeSkill)
 			local durationMod = m_max(calcLib.mod(skillModList, dotCfg, "EnemyIgniteDuration", "SkillAndDamagingAilmentDuration") * calcLib.mod(enemyDB, nil, "SelfIgniteDuration"), 0)
 			globalOutput.IgniteDuration = durationBase * durationMod / rateMod * debuffDurationMult
 			globalOutput.IgniteDuration = globalOutput.IgniteDuration > data.misc.IgniteMinDuration and globalOutput.IgniteDuration or 0
-			local igniteStacks = (globalOutput.IgniteDuration / output.Time) / maxStacks
```
Comment (Regisle) [inline src/Modules/CalcOffence.lua:3213]: you still need to define it as local, either by adding local below, or the better way to do this would be 
local igniteStacks = 1
if not skillData.triggeredOnDeath then
	igniteStacks = (globalOutput.IgniteDuration / output.Time) / maxStacks
end

**Review by LocalIdentity — APPROVED** [review]
