### PR TITLE
Fix outdated modifier text on Aberrath's Hooves

### LINKED ISSUE #2473: Abberath's Hooves Outdated Text
* **What happened?**
Abberath's Hooves still shows the text from Path of Exile 2.5.0.
In patch 2.6.0, "Ignite a nearby Enemy on Killing an Ignited Enemy" (PoB text) became "When you Kill an Ignited Enemy, inflict an equivalent Ignite on each nearby Enemy." (ingame text). Idk if this is just visual or calculated differently based on the wording.
https://pathofexile.fandom.com/wiki/Abberath%27s_Hooves
This is a unique item available in every PoB.
Version: 2.0.3
* **Screenshots:**
image
image

### PR DESCRIPTION
**Pull request by pundm**
fixes #2473 
image
https://www.pathofexile.com/trade/search/Hardcore%20Ritual/xXO4fP

### CODE REVIEW

File: src/Data/Uniques/boots.lua [hunk 1]
```diff
@@ -153,11 +153,11 @@ Enemies can have 1 additional Curse
 Abberath's Hooves
 Goathide Boots
 Requires Level 12, 26 Dex
+Triggers level 7 Abberath's Fury when equipped
```
Comment (ppoelzl) [inline src/Data/Uniques/boots.lua:156]:
```suggestion
Triggers Level 7 Abberath's Fury when Equipped
```

**Review by ppoelzl — COMMENTED** [review]
Capitalisation errors in your shifted line.

**Review by ppoelzl — APPROVED** [review]
