### PR TITLE
Fixes #1741 - Adding separation of rune daggers, warstaves, and convoking wand

### LINKED ISSUE #1741: Missing mods and invalid combinations for newer base types
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
I went to craft a staff with +2 to socketed fire gems, but found that the mod did not exist when crafting it in PoB.  Upon further investigation, I found there were several other special base types that did not have mods available that they should or have mods available that they shouldn't.
* **What steps will reproduce the bug?**
  * Create a warstaff (military staff, for example) and notice that "+2 to socketed fire gems" does not appear in the list of prefixes
  * Create a Convoking wand and notice that "+1 to all minion gems" does not appear as a prefix
  * Create a dagger or a warstaff and notice that spell damage modifiers appear as prefix options, even though they shouldn't
* **Does it reproduce every time?**
Yes
* **Provide a build code:**
Here is a build with a perfectly valid item from the trade website that is unable to be crafted from scratch in PoB:
https://pastebin.com/MUD085Sz
Always provide a build code that exhibits the bug you want to report, even if it is not specific to a particular build. This helps us greatly to reproduce bugs faster. Otherwise, we will have to ask you for the code first before investigating, which would delay any possible fixes.

It seems the fix for this will either require splitting warstaffs and rune daggers out into separate base types, and convoking wands may need special logic (so we don't have a class of items with a single base in it)

### PR DESCRIPTION
**Pull request by Wires77**
This takes care of many mod issues laid out in the issue.  The only remaining issue is Convoking Wand appears twice, but PoB takes the last one so it still works.  It's easily fixed, but I have to specify each and every type to do so

### CODE REVIEW

**Comment by Wires77** [comment]
I've removed the duplicate convoking wand, so this is ready for review.

File: Export/Scripts/bases.lua [hunk 1]
```diff
@@ -164,7 +164,11 @@ directiveTable.base = function(state, args, out)
 end
 
 directiveTable.baseMatch = function(state, args, out)
-	for i, baseItemType in ipairs(dat("BaseItemTypes"):GetRowList("Id", args, true)) do
+	local key = "Id"
+	if args:match("Abstract") then
```
Comment (Wires77) [inline Export/Scripts/bases.lua:168]: This is most definitely a hack, it might be better to change every matcher to look at the BaseType column instead of Id, but then I'd have to change all of the .txt files and it'd be a bigger change than this PR was intended for.  Definitely better for future proofing, though.  I think some special logic would be needed for flasks, but that might be it

Comment (Wires77) [reply Export/Scripts/bases.lua]: Ok, I found a way to make it better without having to change too much

**Review by ppoelzl — APPROVED** [review]
LGTM after the latest changes.
